name: Exportar imagem para o DockerHub
on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Login no DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da imagem Docker
        run: docker build -t myimage .

      - name: Tag da imagem Docker
        run: docker tag myimage ${{ secrets.DOCKERHUB_USERNAME }}/teste:latest

      - name: Push da imagem Docker para o DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/teste:latest
