name: Export to DockerHub
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Export
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Build and Tag Docker image
        run: |
          docker build -t your-image-name .
          docker tag your-image-name ${{ secrets.DOCKER_USER }}/your-repo-name:latest

      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/teste:latest
