name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  
  build:
    
    runs-on: unbuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}$
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}$
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag teste2023/teste:$(date +%s)
      
    - name: Docker push
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}$/teste
